services:
  db:
    platform: linux/arm64
    image: mysql:8.0
    container_name: bm-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=password
    command: mysqld --default-authentication-plugin=mysql_native_password
  app:
    platform: linux/arm64
    environment:
      - TZ=${TZ}
      - BUCKY_DB_USERNAME=${BUCKY_DB_USERNAME:-root}
      - BUCKY_DB_PASSWORD=${BUCKY_DB_PASSWORD:-password}
      - BUCKY_DB_HOSTNAME=${BUCKY_DB_HOSTNAME:-db}
    depends_on:
      - db

volumes:
  mysql_data:

